//go:build !ignore_autogenerated

/*
Copyright 2024 The Flink Chaos Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all fields of ActionSpec into out. in must not be nil.
func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	if in.GracePeriodSeconds != nil {
		val := *in.GracePeriodSeconds
		out.GracePeriodSeconds = &val
	}
}

// DeepCopy returns a deep copy of ActionSpec.
func (in *ActionSpec) DeepCopy() *ActionSpec {
	if in == nil {
		return nil
	}
	out := new(ActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of EphemeralContainerRecord into out. in must not be nil.
func (in *EphemeralContainerRecord) DeepCopyInto(out *EphemeralContainerRecord) {
	*out = *in
	if in.InjectedAt != nil {
		t := *in.InjectedAt
		out.InjectedAt = &t
	}
}

// DeepCopy returns a deep copy of EphemeralContainerRecord.
func (in *EphemeralContainerRecord) DeepCopy() *EphemeralContainerRecord {
	if in == nil {
		return nil
	}
	out := new(EphemeralContainerRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ExternalTarget into out. in must not be nil.
func (in *ExternalTarget) DeepCopyInto(out *ExternalTarget) {
	*out = *in
}

// DeepCopy returns a deep copy of ExternalTarget.
func (in *ExternalTarget) DeepCopy() *ExternalTarget {
	if in == nil {
		return nil
	}
	out := new(ExternalTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of NetworkChaosSpec into out. in must not be nil.
func (in *NetworkChaosSpec) DeepCopyInto(out *NetworkChaosSpec) {
	*out = *in
	if in.ExternalEndpoint != nil {
		out.ExternalEndpoint = in.ExternalEndpoint.DeepCopy()
	}
	if in.Latency != nil {
		d := *in.Latency
		out.Latency = &d
	}
	if in.Jitter != nil {
		d := *in.Jitter
		out.Jitter = &d
	}
	if in.Loss != nil {
		v := *in.Loss
		out.Loss = &v
	}
	if in.Duration != nil {
		d := *in.Duration
		out.Duration = &d
	}
}

// DeepCopy returns a deep copy of NetworkChaosSpec.
func (in *NetworkChaosSpec) DeepCopy() *NetworkChaosSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkChaosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ChaosRun into out. in must not be nil.
func (in *ChaosRun) DeepCopyInto(out *ChaosRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of ChaosRun.
func (in *ChaosRun) DeepCopy() *ChaosRun {
	if in == nil {
		return nil
	}
	out := new(ChaosRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for ChaosRun.
func (in *ChaosRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields of ChaosRunList into out. in must not be nil.
func (in *ChaosRunList) DeepCopyInto(out *ChaosRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]ChaosRun, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

// DeepCopy returns a deep copy of ChaosRunList.
func (in *ChaosRunList) DeepCopy() *ChaosRunList {
	if in == nil {
		return nil
	}
	out := new(ChaosRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for ChaosRunList.
func (in *ChaosRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all fields of ChaosRunSpec into out. in must not be nil.
func (in *ChaosRunSpec) DeepCopyInto(out *ChaosRunSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Scenario.DeepCopyInto(&out.Scenario)
	in.Observe.DeepCopyInto(&out.Observe)
	in.Safety.DeepCopyInto(&out.Safety)
	out.Control = in.Control
}

// DeepCopy returns a deep copy of ChaosRunSpec.
func (in *ChaosRunSpec) DeepCopy() *ChaosRunSpec {
	if in == nil {
		return nil
	}
	out := new(ChaosRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ChaosRunStatus into out. in must not be nil.
func (in *ChaosRunStatus) DeepCopyInto(out *ChaosRunStatus) {
	*out = *in
	if in.StartedAt != nil {
		t := *in.StartedAt
		out.StartedAt = &t
	}
	if in.ObservingStartedAt != nil {
		t := *in.ObservingStartedAt
		out.ObservingStartedAt = &t
	}
	if in.EndedAt != nil {
		t := *in.EndedAt
		out.EndedAt = &t
	}
	if in.SelectedPods != nil {
		pods := make([]string, len(in.SelectedPods))
		copy(pods, in.SelectedPods)
		out.SelectedPods = pods
	}
	if in.InjectedPods != nil {
		pods := make([]string, len(in.InjectedPods))
		copy(pods, in.InjectedPods)
		out.InjectedPods = pods
	}
	if in.TargetSummary != nil {
		ts := *in.TargetSummary
		out.TargetSummary = &ts
	}
	if in.Observation != nil {
		obs := new(ObservationStatus)
		in.Observation.DeepCopyInto(obs)
		out.Observation = obs
	}
	if in.NetworkPolicies != nil {
		nps := make([]string, len(in.NetworkPolicies))
		copy(nps, in.NetworkPolicies)
		out.NetworkPolicies = nps
	}
	if in.EphemeralContainerInjections != nil {
		recs := make([]EphemeralContainerRecord, len(in.EphemeralContainerInjections))
		for i := range in.EphemeralContainerInjections {
			in.EphemeralContainerInjections[i].DeepCopyInto(&recs[i])
		}
		out.EphemeralContainerInjections = recs
	}
	if in.ResourceExhaustionInjections != nil {
		recs := make([]EphemeralContainerRecord, len(in.ResourceExhaustionInjections))
		for i := range in.ResourceExhaustionInjections {
			in.ResourceExhaustionInjections[i].DeepCopyInto(&recs[i])
		}
		out.ResourceExhaustionInjections = recs
	}
	if in.Conditions != nil {
		conds := make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&conds[i])
		}
		out.Conditions = conds
	}
}

// DeepCopy returns a deep copy of ChaosRunStatus.
func (in *ChaosRunStatus) DeepCopy() *ChaosRunStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ControlSpec into out. in must not be nil.
func (in *ControlSpec) DeepCopyInto(out *ControlSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of ControlSpec.
func (in *ControlSpec) DeepCopy() *ControlSpec {
	if in == nil {
		return nil
	}
	out := new(ControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of FlinkRestObserve into out. in must not be nil.
func (in *FlinkRestObserve) DeepCopyInto(out *FlinkRestObserve) {
	*out = *in
	if in.CheckpointWaitTimeout != nil {
		d := *in.CheckpointWaitTimeout
		out.CheckpointWaitTimeout = &d
	}
}

// DeepCopy returns a deep copy of FlinkRestObserve.
func (in *FlinkRestObserve) DeepCopy() *FlinkRestObserve {
	if in == nil {
		return nil
	}
	out := new(FlinkRestObserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ObservationStatus into out. in must not be nil.
func (in *ObservationStatus) DeepCopyInto(out *ObservationStatus) {
	*out = *in
	if in.RecoveryObservedAt != nil {
		t := *in.RecoveryObservedAt
		out.RecoveryObservedAt = &t
	}
	if in.RecoveryTimeSeconds != nil {
		v := *in.RecoveryTimeSeconds
		out.RecoveryTimeSeconds = &v
	}
}

// DeepCopy returns a deep copy of ObservationStatus.
func (in *ObservationStatus) DeepCopy() *ObservationStatus {
	if in == nil {
		return nil
	}
	out := new(ObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ObserveSpec into out. in must not be nil.
func (in *ObserveSpec) DeepCopyInto(out *ObserveSpec) {
	*out = *in
	in.FlinkRest.DeepCopyInto(&out.FlinkRest)
}

// DeepCopy returns a deep copy of ObserveSpec.
func (in *ObserveSpec) DeepCopy() *ObserveSpec {
	if in == nil {
		return nil
	}
	out := new(ObserveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ResourceExhaustionSpec into out. in must not be nil.
func (in *ResourceExhaustionSpec) DeepCopyInto(out *ResourceExhaustionSpec) {
	*out = *in
	if in.Duration != nil {
		d := *in.Duration
		out.Duration = &d
	}
}

// DeepCopy returns a deep copy of ResourceExhaustionSpec.
func (in *ResourceExhaustionSpec) DeepCopy() *ResourceExhaustionSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceExhaustionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of SafetySpec into out. in must not be nil.
func (in *SafetySpec) DeepCopyInto(out *SafetySpec) {
	*out = *in
	if in.MinTaskManagersRemaining != nil {
		v := *in.MinTaskManagersRemaining
		out.MinTaskManagersRemaining = &v
	}
	if in.MaxNetworkChaosDuration != nil {
		d := *in.MaxNetworkChaosDuration
		out.MaxNetworkChaosDuration = &d
	}
	if in.MaxResourceExhaustionDuration != nil {
		d := *in.MaxResourceExhaustionDuration
		out.MaxResourceExhaustionDuration = &d
	}
}

// DeepCopy returns a deep copy of SafetySpec.
func (in *SafetySpec) DeepCopy() *SafetySpec {
	if in == nil {
		return nil
	}
	out := new(SafetySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of ScenarioSpec into out. in must not be nil.
func (in *ScenarioSpec) DeepCopyInto(out *ScenarioSpec) {
	*out = *in
	in.Selection.DeepCopyInto(&out.Selection)
	in.Action.DeepCopyInto(&out.Action)
	if in.Network != nil {
		out.Network = in.Network.DeepCopy()
	}
	if in.ResourceExhaustion != nil {
		out.ResourceExhaustion = in.ResourceExhaustion.DeepCopy()
	}
}

// DeepCopy returns a deep copy of ScenarioSpec.
func (in *ScenarioSpec) DeepCopy() *ScenarioSpec {
	if in == nil {
		return nil
	}
	out := new(ScenarioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of SelectionSpec into out. in must not be nil.
func (in *SelectionSpec) DeepCopyInto(out *SelectionSpec) {
	*out = *in
	if in.PodNames != nil {
		names := make([]string, len(in.PodNames))
		copy(names, in.PodNames)
		out.PodNames = names
	}
}

// DeepCopy returns a deep copy of SelectionSpec.
func (in *SelectionSpec) DeepCopy() *SelectionSpec {
	if in == nil {
		return nil
	}
	out := new(SelectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of TargetSpec into out. in must not be nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.Selector != nil {
		out.Selector = in.Selector.DeepCopy()
	}
}

// DeepCopy returns a deep copy of TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of TargetSummary into out. in must not be nil.
func (in *TargetSummary) DeepCopyInto(out *TargetSummary) {
	*out = *in
}

// DeepCopy returns a deep copy of TargetSummary.
func (in *TargetSummary) DeepCopy() *TargetSummary {
	if in == nil {
		return nil
	}
	out := new(TargetSummary)
	in.DeepCopyInto(out)
	return out
}
